# Generated by Django 5.0.4 on 2026-04-04 03:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ComparisonReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "metrics_data",
                    models.JSONField(help_text="Aggregated metrics for all algorithms"),
                ),
                (
                    "ranking",
                    models.JSONField(help_text="Algorithm ranking based on metrics"),
                ),
                (
                    "winner",
                    models.CharField(
                        help_text="Best performing algorithm", max_length=20
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_final",
                    models.BooleanField(
                        default=False, help_text="Mark as final comparison"
                    ),
                ),
            ],
            options={
                "db_table": "comparison_reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AlgorithmMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "algorithm",
                    models.CharField(
                        choices=[
                            ("content_based", "Content-Based Filtering"),
                            ("user_based_cf", "User-Based Collaborative Filtering"),
                            ("item_based_cf", "Item-Based Collaborative Filtering"),
                            ("svd", "SVD Matrix Factorization"),
                            ("hybrid", "Hybrid Recommendation System"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date", models.DateField()),
                ("impressions", models.PositiveIntegerField(default=0)),
                ("clicks", models.PositiveIntegerField(default=0)),
                ("add_to_carts", models.PositiveIntegerField(default=0)),
                ("purchases", models.PositiveIntegerField(default=0)),
                ("ctr", models.FloatField(default=0.0, help_text="Click-through rate")),
                (
                    "conversion_rate",
                    models.FloatField(default=0.0, help_text="Conversion rate"),
                ),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "avg_order_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("precision", models.FloatField(blank=True, default=0.0, null=True)),
                ("recall", models.FloatField(blank=True, default=0.0, null=True)),
                ("f1_score", models.FloatField(blank=True, default=0.0, null=True)),
                ("ndcg", models.FloatField(blank=True, default=0.0, null=True)),
                ("diversity", models.FloatField(blank=True, default=0.0, null=True)),
                ("coverage", models.FloatField(blank=True, default=0.0, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "algorithm_metrics",
                "ordering": ["-date", "algorithm"],
                "unique_together": {("algorithm", "date")},
            },
        ),
    ]
