# Generated by Django 5.0.4 on 2026-06-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithmmetrics',
            name='hit_rate',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
