# Generated by Django 5.0.4 on 2026-04-04 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecommendationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "algorithm",
                    models.CharField(
                        choices=[
                            ("content_based", "Content-Based Filtering"),
                            ("user_based_cf", "User-Based Collaborative Filtering"),
                            ("item_based_cf", "Item-Based Collaborative Filtering"),
                            ("svd", "SVD Matrix Factorization"),
                            ("hybrid", "Hybrid Recommendation System"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("impression", "Impression"),
                            ("click", "Click"),
                            ("add_to_cart", "Add to Cart"),
                            ("purchase", "Purchase"),
                        ],
                        max_length=20,
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                (
                    "revenue",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation_events",
                        to="products.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendation_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "recommendation_events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["algorithm", "event_type"],
                        name="recommendat_algorit_450fee_idx",
                    ),
                    models.Index(
                        fields=["algorithm", "created_at"],
                        name="recommendat_algorit_cd7835_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("view", "Product View"),
                            ("click", "Recommendation Click"),
                            ("add_to_cart", "Add to Cart"),
                            ("purchase", "Purchase"),
                            ("review", "Review"),
                            ("wishlist", "Wishlist"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "weight",
                    models.FloatField(
                        default=1.0, help_text="Interaction weight for algorithms"
                    ),
                ),
                (
                    "algorithm_used",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("content_based", "Content-Based Filtering"),
                            ("user_based_cf", "User-Based Collaborative Filtering"),
                            ("item_based_cf", "Item-Based Collaborative Filtering"),
                            ("svd", "SVD Matrix Factorization"),
                            ("hybrid", "Hybrid Recommendation System"),
                        ],
                        help_text="Which algorithm led to this interaction (if applicable)",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_interactions",
                        to="products.product",
                    ),
                ),
                (
                    "target_product",
                    models.ForeignKey(
                        blank=True,
                        help_text="For recommendation clicks, the product that was recommended",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_interactions",
                        to="products.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_interactions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "interaction_type"],
                        name="user_intera_user_id_5f7a30_idx",
                    ),
                    models.Index(
                        fields=["product", "interaction_type"],
                        name="user_intera_product_30a724_idx",
                    ),
                ],
            },
        ),
    ]
